name: Node.js Package

on:
  push:
    branches:
      - main

jobs:
  publish-package:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.15.1
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}

      - run: npm install
      - run: npm run build
      - run: touch .npmrc
      - run: |
          echo '//npm.pkg.github.com/:_authToken=${{NPM_TOKEN}}' >> ./.npmrc
      - run: npm run test
      - run: npm publish
